language: objective-c
osx_image: xcode8
env:
  - PLATFORM="ios" SCHEME="Noosh" TARGET="NooshTests" DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=10.0" SDK="iphonesimulator10.0"
before_install:
  - pod repo update
before_script:
  - xcodebuild -workspace Noosh.xcworkspace -list
  - instruments -s devices
script:
  - xcodebuild -workspace Noosh.xcworkspace -scheme $SCHEME -destination "$DESTINATION" -sdk "$SDK" -configuration Debug build test

