language: objective-c
osx_image: xcode8.2
env:
  - PLATFORM="ios" SCHEME="Noosh" TARGET="NooshTests" DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=10.2" SDK="iphonesimulator10.2"
before_install:
  - pod repo update > /dev/null
  - pod install
before_script:
  - xcodebuild -workspace Noosh.xcworkspace -list
  - instruments -s devices
script:
  - set -o pipefail
  - xcodebuild -workspace Noosh.xcworkspace -scheme $SCHEME -destination "$DESTINATION" -sdk "$SDK" build test

