language: objective-c
osx_image: xcode8.2
before_install:
  - brew install xctool
  - pod repo update > /dev/null
  - pod install
before_script:
  - xcodebuild -workspace Noosh.xcworkspace -list
  - instruments -s devices
script:
  - set -o pipefail
  - xctool -workspace Noosh.xcworkspace -scheme Noosh run-tests -test-sdk iphonesimulator10.2

